### ISSUE TITLE
Regression in member administration

### ISSUE THREAD

**Issue by elhaard** [dsroklub/roprotokol#23]
Member rights are shown incorrectly, just a list of numbers.
It is unknown whether adding member rights works.

![image](https://cloud.githubusercontent.com/assets/382397/15533901/d280dfc0-2266-11e6-927d-655f5eed9530.png)

**Comment by elhaard** [comment]
Please inform Steen Kn udsen when this is fixed.

**Comment by elgaard** [comment]
fixed
