### ISSUE TITLE
Indication of selected main menu item

### ISSUE THREAD

**Issue by elhaard** [dsroklub/roprotokol#24]
It should be clearly visible which menu item (Udskrivning, Indskrivning, etc.) you have selected. 

Marking the selected menu item with a darker background color would be fine.

**Comment by elgaard** [comment]
done.
could be prettier. Should be styled better.

**Comment by elhaard** [comment]
Den 25-05-2016 kl. 16:35 skrev Niels Elgaard Larsen:

> Closed #24 https://github.com/dsroklub/roprotokol/issues/24.

frontend/app/controllers/menu.js ???
- J

**Comment by elgaard** [comment]
nu i git
