### ISSUE TITLE
Sorting of rowers is wrong on "rovagt" page

### ISSUE THREAD

**Issue by elhaard** [dsroklub/roprotokol#26]
Under the "Rovagt" tab, the sorting of rowers is wrong - at least for "Dagens ture", but possibly also for "På vandet".

**Comment by elgaard** [comment]
Det ser da ellers ud til at virke. Hvile ture vises forkert?

**Comment by elhaard** [comment]
Den 24-06-2016 kl. 23:47 skrev Niels Elgaard Larsen:

> Det ser da ellers ud til at virke. Hvile ture vises forkert?

Det virker nogle gange.

Jeg prøvede netop at gå ind på Rovagt. Der blev det vist korrekt. Så
oprettede jeg en tur og gik ind på rovagt igen. Denne gang blev dagens
ture vist forkert - se f.x. turen med Ask på vedhæftede screenshot.

Sammenlign med, hvordan den ser ud under Ture.
- Jørgen

**Comment by elgaard** [comment]
Jeg kan ikke se noget screeenshot

**Comment by elgaard** [comment]
Nu har jeg tilføjet mere sortering
